/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.deploy.jsonc --include-runtime false` (hash: 9dd8d1f349b1ba39c46618ea430668ea)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	AI: Ai;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
